unbind C-b
set -g prefix C-a

# bind key 'prefix + r' for reloading .tmux.conf file
bind-key r source-file ~/.tmux.conf \; display-message ".tmux.conf has been reloaded"

bind-key -n C-h select-pane -L
bind-key -n C-k select-pane -U
bind-key -n C-j select-pane -D
bind-key -n C-l select-pane -R

# set color to match terminal default color
set-option -g default-terminal "screen-256color"

# set color for tmux status bar
set -g status-bg "#5f5f5f"
set -g status-fg "#ffffff"

# set status bar text
set -g status-left-length 50
set -g status-right "#[fg=brightgreen]#(pmset -g batt | awk -F '(\t|;)' 'NR==2 {print $2, $3}') |#[default] Pane: #P | #(date '+%a, %b %d - %I:%M')"

# bind key for splitting windows
bind-key - split-window -v -c '#{pane_current_path}'
bind-key \\ split-window -h -c '#{pane_current_path}'

# bind key for resizing panes
bind -n S-Left resize-pane -L 2
bind -n S-Right resize-pane -R 2
bind -n S-Down resize-pane -D 2
bind -n S-Up resize-pane -U 2

# bind key for new window
bind c new-window -c "#{pane_current_path}"

# set window index start from 1
set-option -g base-index 1
set-option -g renumber-windows on

# bind break pane with detach mode
bind-key b break-pane -d

# bind key for choose-tree
bind-key C-j choose-tree

# Use vim keybindings in copy mode
setw -g mode-keys vi

# Setup 'v' to begin selection as in Vim
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

# Update default binding of `Enter` to also use copy-pipe
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
